# playbooks/verificar_apache.yml
- name: Verificar y corregir la configuración de Apache
  hosts: all
  tasks:
    - name: Asegurarse de que Apache esté escuchando en el puerto 80
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen 80'
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: httpd
        state: restarted