- name: Verificar y restaurar el archivo /etc/hosts
  hosts: vm2
  become: yes  # Añadir esta línea para elevar privilegios
  tasks:
    - name: Comparar el archivo /etc/hosts con el original
      ansible.builtin.command: diff /etc/hosts /usr/local/etc/hosts_original
      register: diff_output
      changed_when: diff_output.rc == 1  # Marcar como cambiado si hay diferencias

    - name: Restaurar el archivo /etc/hosts si es diferente
      ansible.builtin.copy:
        src: /usr/local/etc/hosts_original
        dest: /etc/hosts
        mode: '0644'
      when: diff_output.rc == 1
      notify:
        - Log restore