# ---
# - name: reconfigure Apache if not running
#   hosts: vm2
#   become: yes
#   tasks:
#     - name: Apply configuration if Apache is not running
#       block:
#         - name: Apply Apache configuration
#           copy:
#             src: /etc/apache2/apache.conf 
#             dest: /etc/apache2/sites-available/000-default.conf
#             mode: '0644'
#             remote_src: yes

#         - name: Restart Apache service
#           service:
#             name: apache2
#             state: restarted
#             enabled: yes

#     - name: Ensure Apache is running and enabled
#       service:
#         name: apache2
#         state: started
#         enabled: yes


---
- name: Ensure Apache is configured and running
  hosts: vm2
  become: yes
  tasks:
    - name: Ensure Apache is listening on port 80
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 80'
      notify:
        - Restart Apache

    - name: Apply Apache configuration
      copy:
        src: /etc/apache2/apache.conf 
        dest: /etc/apache2/sites-available/000-default.conf
        mode: '0644'
        remote_src: yes
      notify:
        - Restart Apache

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted