---
- name: Reemplazar apache.conf sobre apache2.conf 
  hosts: vm2
  become: yes
  tasks:
    - name: Copiar apache.conf sobre apache2.conf
      copy:
        src: /etc/apache2/apache2-original.conf
        dest: /etc/apache2/apache2.conf
        remote_src: yes