---
- name: Verify and reconfigure Apache if not running
  hosts: vm2
  become: yes
  tasks:
    - name: Check if Apache is running
      shell: systemctl is-active apache2
      register: apache_status
      ignore_errors: yes

    - name: Apply configuration if Apache is not running
      block:
        - name: Apply Apache configuration
          copy:
            src: /etc/apache2/apache.conf 
            dest: /etc/apache2/sites-available/000-default.conf
            mode: '0644'
            remote_src: yes

        - name: Restart Apache service
          service:
            name: apache2
            state: restarted
            enabled: yes
      when: apache_status.stdout != "active"

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
