---
- name: Verificar si los archivos son iguales
  hosts: vm2
  become: yes
  tasks:
    - name: Verificar si los archivos son iguales
      command: diff /etc/apache2/apache2.conf /etc/apache2/sites-available/000-default.conf
      register: diff_result
      ignore_errors: yes

    - name: Mostrar mensaje de éxito si los archivos son iguales
      debug:
        msg: "Los archivos son iguales: SUCCESS"
      when: diff_result.rc == 0

    - name: Mostrar mensaje de fallo si los archivos no son iguales
      debug:
        msg: "Los archivos no son iguales: FAILED"
      when: diff_result.rc != 0
