- name: Verificar y restaurar el archivo /etc/hosts
  hosts: vm2
  become: yes
  tasks:
    - name: Comparar el archivo /etc/hosts con el original
      ansible.builtin.command: diff /etc/hosts /usr/local/etc/hosts_original
      register: diff_output
      failed_when: diff_output.rc != 0
      changed_when: false
