---
- name: Verificar si los archivos son iguales
  hosts: vm2
  become: yes
  tasks:
    - name: Verificar si los archivos son iguales
      ansible.builtin.command: diff /etc/apache2/apache2.conf /etc/apache2/apache2-original.conf
      register: diff_output
      ignore_errors: yes

    - name: Mostrar mensaje de éxito si los archivos son iguales
      ansible.builtin.debug:
        msg: "Los archivos son iguales: SUCCESS"
      when: diff_output.rc == 0

    - name: Mostrar mensaje de fallo si los archivos no son iguales
      ansible.builtin.debug:
        msg: "Los archivos no son iguales: FAILED"
      when: diff_output.rc != 0