- name: Check web server configuration
  hosts: all
  become: yes
  tasks:
    - name: Check if Apache is installed
      shell: dpkg-query -W -f='${Status}' apache2
      register: apache_installed
      changed_when: false
      failed_when: "'install ok installed' not in apache_installed.stdout"

    - name: Check if Apache service is running
      shell: systemctl is-active apache2
      register: apache_running
      changed_when: false
      failed_when: apache_running.stdout.strip() != "active"

    - name: Check if Apache service is enabled
      shell: systemctl is-enabled apache2
      register: apache_enabled
      changed_when: false
      failed_when: apache_enabled.stdout.strip() != "enabled"